# Kafka & Schema Registry
bootstrap.servers=kafka:19092
schema.registry.url=http://kafka:8081
hoodie.streamer.schemaprovider.registry.url=http://kafka:8081/subjects/processed_orders-value/versions/latest
hoodie.streamer.source.kafka.topic=processed_orders
hoodie.streamer.source.kafka.value.deserializer.class=io.confluent.kafka.serializers.KafkaAvroDeserializer

# Hudi Keys
hoodie.datasource.write.recordkey.field=order_number
hoodie.datasource.write.precombine.field=order_number
hoodie.datasource.write.partitionpath.field=

# Hive Sync
hoodie.datasource.hive_sync.enable=true
hoodie.datasource.hive_sync.mode=hms
hoodie.datasource.hive_sync.metastore.uris=thrift://hive-metastore:9083
hoodie.datasource.hive_sync.database=default
hoodie.datasource.hive_sync.table=processed_orders
