CREATE TABLE `geom` (
  `id` int NOT NULL AUTO_INCREMENT,
  `g` geometry NOT NULL,
  `h` geometry DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;